### PR TITLE
jump to a worker in anchor in url and highlight it

### PR DESCRIPTION
**Pull request by mahakporwal02**
## Rationale

[//]: # (Briefly explain the reason behind this change.)

#461 
## Changes
I have added `scrollTo` function in `updated` in workersView as it was not scrolling by normal archoring in url as it was jumping to the worker even before the page was completely loaded,I have also added a bootstrap class to the worker name to show it highlighted

Now after the page is loaded it will jump to the worker with id same as anchor of url and will highlight it @kelson42 @rgaudin

### CODE REVIEW

**Comment by rgaudin** [comment]
Thank you @mahakporwal02 ; works I expected (I guess). Two remarks:

- shouldn't you add links to worker names so that there are clickable? Having to type this manually kind of defeat the purpose I think.
- Can we do it without another external dependency? Dependencies are a nightmare to track and maintain and that feature seems both simple and relatively futile so I'd prefer we don't add another dep for it.

**Comment by mahakporwal02** [comment]
@rgaudin 
1)I have made the required changes about clickable worker name
2)We have to use dep for scrolling in vue as the function has to be performed after the page being completed loaded

**Comment by rgaudin** [comment]
@mahakporwal02 sorry your explanation is not enough. Look at what the dep does and check whether we can implement the part that interest us in our code.

Also, don't rewrite commits until your PR is accepted as it's impossible to review what's changed ; so I must re-review the whole thing

**Comment by mahakporwal02** [comment]
@rgaudin pls review the changes

**Comment by rgaudin** [comment]
@mahakporwal02 thank you for the update but it's not working for me. Highlighting works fine but it doesn't scroll…

**Comment by mahakporwal02** [comment]
@rgaudin pls review it

**Comment by rgaudin** [comment]
Thanks ; it's now working!
Can you please adjust code formatting so it's similar to the rest of the code base: spaces around operators ; no space before trailing `;` ; same indentation, comment on top of line.

Will merge as soon as it's done.

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
