### PR TITLE
Add new black formatting

### PR DESCRIPTION
**Pull request by satyamtg**
Adds new formatting from black 20.8

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
black in CI must be updated as well (using updated action?)

**Comment by satyamtg** [comment]
> black in CI must be updated as well (using updated action?)

I browsed the marketplace and there doesn't seem to be an action using black 20.8b1 . Have created https://github.com/jpetrucciani/black-check/issues/1 for the same.

**Comment by rgaudin** [comment]
> > black in CI must be updated as well (using updated action?)
> 
> I browsed the marketplace and there doesn't seem to be an action using black 20.8b1 . Have created [jpetrucciani/black-check#1](https://github.com/jpetrucciani/black-check/issues/1) for the same.

Then we can remove the action and add a regular step install it via pip

**Comment by rgaudin** [comment]
thanks ; specified min version and used `black --check`

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
