### PR TITLE
Help buttons

### LINKED ISSUE #889: Propose systematically a link to the scraper manual/faq in the recipe view
Somewhere in the recipe configuration, probably at the location in the screenshot below, we should have a link to the scraper manual / FAQ so that it is easier to find.

image

### LINKED ISSUE #890: In the recipe meta form, propose a link to corresponding documentation
Somewhere in the recipe configuration, probably at the location in the screenshot below, we should have a link to a generic documentation about all these parameters.

image

### PR DESCRIPTION
**Pull request by benoit74**
## Rationale

Fix #889 
Fix #890 

## Changes

- Modify `GET /offliner/{offliner}` endpoint:
  - Move array to `flags` property (it is generally considered a bad design to return arrays as root JSON objects anyway)
  - Add a `help` property which is the URL of the help to configure given offliner
    - Always computed as `https://github.com/openzim/{offliner}/wiki/Frequently-Asked-Questions` for now, but could be more specific later on, at least for few offliners
    - Could be reused in other frontend (e.g. zimit-frontend), hence adding it to the backend (rather than the frontend) makes sense

| Before | After |
|---|---|
| image | image |

- Add 3 help buttons and two dividers

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Comment by benoit74** [comment]
FYI again, the Help button in "Content settings" section leads to https://github.com/openzim/zimfarm/wiki/Recipe-configuration-%E2%80%90-Content-settings and the Help button in "Task settings" section leads to https://github.com/openzim/zimfarm/wiki/Recipe-configuration-%E2%80%90-Task-settings. Both are freshly created and mostly placeholders for now.

**Comment by Popolechien** [comment]
> does the new "Help" buttons in the UI match your expectations 

LGTM

**Review by rgaudin — APPROVED** [review]
Thank you ; 
Something bothers me with the new label (Content/Task/Scrapper) but I can't find any better ones and those headers improve readiness 👍

**Comment by benoit74** [comment]
> Something bothers me with the new label (Content/Task/Scrapper) but I can't find any better ones and those headers improve readiness 👍

They bother me as well, but I can't find better ones either! ^^

**Comment by Popolechien** [comment]
Some of the fields should probably be moved about so that they better match the content / task and scraper titles (`periodicity` should move to Task for instance; `Scraper settings` could be _`Name`_` scraper settings` as we have now (and remove `Command flags` so as to keep the title consistent)

**Comment by benoit74** [comment]
> Some of the fields should probably be moved about so that they better match the content / task and scraper titles (periodicity should move to Task for instance; Scraper settings could be Name settings as we have now (and remove Command flags so as to keep the title consistent)

@Popolechien I don't mind if you want to move fields, but this is a new issue, please create one with a more precise proposition than  "some ... should ..." and the reasoning behind it. Since this current PR / change LGTY, I will merge it for now, we can always continue to enhance it afterwards.

**Comment by Popolechien** [comment]
@benoit74 Yeah it wasn't an actual request but more a generic response to the "Something bothers me with the new label" comment. Thanks.

**Comment by kelson42** [comment]
@benoit74 thx for the PR... I share the "bad feeling" expressed

**Pull request merged**
