### PR TITLE
Docs suggestion

### PR DESCRIPTION
**Pull request by EladKeyshawn**
Hey all! 
Here are some suggestions for this project specifically for docs/. Also there some unclear things like frontend/ etc that should be explained and documented as well. I'd love to help 😄

### CODE REVIEW

**Comment by EladKeyshawn** [comment]
@automactic Yep indeed its just a good start.

**Comment by automactic** [comment]
@EladKeyshawn, would it be helpful if I give you examples like [this](https://paw.pt/cxN4DJdK)

**Comment by EladKeyshawn** [comment]
@automactic Yeah that's really helpful since in my dev env not everything's working correctly.

**Comment by automactic** [comment]
Wait, what? Can you be more specific about what is not working?

**Comment by EladKeyshawn** [comment]
@automactic No I meant that some things are not fully clear to me. Like where can I find admin email so I can test task/mwoffliner

**Comment by EladKeyshawn** [comment]
as well as how the frontend/ comes into the picture

**Comment by automactic** [comment]
You can find the preconfigured username and passwords in [config.yml](https://github.com/openzim/zimfarm/blob/dispatcher-enhancement/dispatcher/config.yml)

Frontend will become another container alongside backend and together proxied as a single site. So, for example, if you are running at localhost and using default port `8080`. The frontend will be at `localhost:8080`, backend will be at `localhost:8080/api`

I have it currently running at home. You can visit it [here](https://zimfarm.chrisshwli.com). I know login is not working correctly. I need to fix a lot of things in the frontend caused by the code migration yesterday. But backend totally works! For example, you can send a request like [this](https://paw.pt/cxOf4lH9?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXdwdF9pZCI6ODM4NjM2NzIxNjU2Nywic2NvcGVzIjpbInJlYWQiXSwibm9uY2UiOiIwYzRmZjQxNC1kNzZhLTRhYWItYjIzMy1iNzlhNzFjNGJlMjgifQ.uaMc14E2QKivqrJwQoY6tgsWS0l1kBGkEEzAjRq2SHE) to get a token.

**Comment by EladKeyshawn** [comment]
Yep I auth with the username and password but for assigning tasks its asks for admin email

**Comment by EladKeyshawn** [comment]
Your frontend link you sent looks awesome 😉

**Comment by automactic** [comment]
Thanks! The `adminEmail` is a requirement by mwoffliner. I don't really understand why it needs that, but you could use any email.

**Comment by EladKeyshawn** [comment]
if I just put an email its throws some authentication error, i'll check it out soon enough.

**Comment by kelson42** [comment]
@automactic the adminEmail appears then in the scrapper user-agent. This is to give a soltuion to the mediawiki owner to contact the scrapper admin/Identify who is scrapping.

**Comment by EladKeyshawn** [comment]
@kelson42 cool ;)

**Pull request merged**
