### PR TITLE
Adapt mwoffliner configuration for 1.14

### LINKED ISSUE #990: Migrate to MWoffliner 1.14
We plan to release MWoffliner `3.14` in the next weeks. This new release bring mainly:
* Support of the new `mobile-html` API
* Deprecation of the old `mobile-section` API
* Rearchitecture/Modularisation of the whole scraper based on API end-points
* Few changes in the arguments

Therefore we need to be in general careful with this move and to adapt the ZIMFarm MWoffliner Recipe template.

Here is the diff regarding the path related paramters:
```
-  mwApiPath: 'Mediawiki API path (per default "/w/api.php")',
-  mwRestApiPath: 'Mediawiki Rest API path (per default "/api/rest_v1")',
+  mwActionApiPath: 'MediaWiki API path (by default "/w/api.php")',
+  mwRestApiPath: 'MediaWiki REST API path (by default "/w/rest.php")',
```

In addition we have a new parameter:
+  forceRender:
+    'Force the usage of a specific API end-point/render, automatically chosen otherwise. Accepted values: [ VisualEditor, WikimediaDesktop. WikimediaMobile ]. More details at https://github.com/openzim/mwoffliner/wiki/API-end-points',
+  insecure: 'Skip HTTPS server authenticity verification step',

### PR DESCRIPTION
**Pull request by benoit74**
## Rationale

Fix #990

NOTA: it looks like mwRestApiPath is not exposed for now, or I missed it in the code.

This is not ready yet for rollout (1.14 is not yet out), and will need an immediate reconfiguration of the DB to change parameter name from `mwApiPath` to `mwActionApiPath` see https://github.com/kiwix/operations/issues/214

### CODE REVIEW

**Comment by kelson42** [comment]
> NOTA: it looks like mwRestApiPath is not exposed for now, or I missed it in the code.

What do you mean you with that? You mean in the code of MWoffliner? I would like to merge this PR now, so we can move forward?

**Comment by audiodude** [comment]
> > NOTA: it looks like mwRestApiPath is not exposed for now, or I missed it in the code.
> 
> What do you mean you with that? You mean in the code of MWoffliner? I would like to merge this PR now, so we can move forward?

@benoit74 do you mean https://github.com/openzim/mwoffliner/blob/main/src/parameterList.ts#L21 ?

**Comment by benoit74** [comment]
> What do you mean you with that? You mean in the code of MWoffliner? 

I mean that `mwRestApiPath` was already a parameter in 1.13 but has not yet been made available on the Zimfarm recipes.

> I would like to merge this PR now, so we can move forward?

We can do it whenever you want, I understood the plan was first to purge the cache and release 1.14, but I don't really mind in fact since all recipes all paused anyway.

Can you please confirm the list of parameters I've added in this PR is correct and that there is no typo?

**Comment by benoit74** [comment]
Let's merge this, it looks like nobody would like to confirm the list of parameters is OK.

**Pull request merged**
