### PR TITLE
mwoffliner-redis connection via socket

### PR DESCRIPTION
**Pull request by rgaudin**
## Rationale

Request in #233 to improve perf/latency/reliability of mwoffliner-redis communication.

## Changes

- uses a busybox container to _host_ the socket (ran per task)
- socket is postfixed with task_id to prevent conflict on host mapping

### CODE REVIEW

**Comment by rgaudin** [comment]
You mean having a single socket container and using `volume_from` from it on all mwo containers?

We've discussed this with @kelson42 and it was agreed that we should, as much as possible, not share resources across tasks, even though that means wasting some resource on the wroker (docker overhead).

I have an upcoming PR with the same structure coming…

that said, the socket is a special case as:

* the resources are a single folder on the host so _isolation_ has no real benefit.
* there's no overhead as we need the _container_ but we don't need it running (we run it to create it but it exits right away)

So it's just a design decision. I like it as a host-feature but I'm fine with having it per-task as well. @kelson42 @automactic, suggestion ?

**Comment by kelson42** [comment]
@rgaudin No

> So it's just a design decision. I like it as a host-feature but I'm fine with having it per-task as well. @kelson42 @automactic, suggestion ?

No, you explained it well. I think this is the most robust way to implement it and that for only a little price (in resources).

**Comment by automactic** [comment]
@rgaudin no I mean like following:
```
redis ----|----- host -------|-----mwoffliner
redis_a <--> redis_a.sock <--> mwoffliner_a
redis_b <--> redis_b.sock <--> mwoffliner_b
redis_c <--> redis_c.sock <--> mwoffliner_c
```

so no need for any socket container, simply map the `redis.sock` to different socket files on host, and map those socket files to corresponding mwoffliner container. Will that work?

**Comment by rgaudin** [comment]
Replaced by #236

**Pull request closed without merging**
