### PR TITLE
cookie should last longer

### PR DESCRIPTION
**Pull request by mahakporwal02**
#588 

[//]: # (Briefly explain the reason behind this change.)
Offline workers reappear automatically

#588 
## Changes
Added expiration time set as 10 years as expiration time cannot be set as infinity.

Now the workers will not appear automatically as expiration time is far long.

### CODE REVIEW

**Comment by kelson42** [comment]
@mahakporwal02 Thank you for your quick fix.
@rgaudin would that make sense to have manybe a kind of coherent strategy regrading cookies expiration time?

**Comment by rgaudin** [comment]
> @rgaudin would that make sense to have manybe a kind of coherent strategy regrading cookies expiration time?

We have 3 cookies:
- pref-limit, for your limit on number of items in pipeline/recipes
- token, for the authentication. this expires after 6months
- onlines-only, for the workers view. With this fix would *never expire* (10y)

Token one is though-through but if you have suggestions for the other two, this PR would be a good opportunity to set them.
We could also use a single preference cookie for both values but that would require some additional changes.

**Comment by kelson42** [comment]
@mahakporwal02 Would you able to add a cookie lifetime configuration (or constant) and rely on it for the two cookies @rgaudin is talking about?

**Comment by mahakporwal02** [comment]
@rgaudin @kelson42 OK, I'll fix it

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
